# Generated by Django 6.0.1 on 2026-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(blank=True, help_text='When the user actually applied', null=True),
        ),
    ]
