# Generated by Django 6.0.1 on 2026-01-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_add_date_rejected'),
        ('applications', '0005_alter_jobapplication_date_applied'),
    ]

    operations = [
    ]
