# Generated by Django 6.0.1 on 2026-01-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
