# Generated by Django 6.0.1 on 2026-01-12 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigeneration',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='aigeneration',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='aigeneration',
            name='prompt_type',
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='generation_type',
            field=models.CharField(choices=[('tailored_resume', 'Tailored Resume'), ('cover_letter', 'Cover Letter'), ('interview_prep', 'Interview Preparation')], default='tailored_resume', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='input_resume',
            field=models.TextField(blank=True, help_text='Original resume text', null=True),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='job_description',
            field=models.TextField(default='tailored_resume', help_text='Job description used for generation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='job_url',
            field=models.URLField(blank=True, help_text='Original job posting URL if scraped', null=True),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='tokens_used',
            field=models.IntegerField(blank=True, help_text='Total tokens consumed', null=True),
        ),
        migrations.AlterField(
            model_name='aigeneration',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='applications.jobapplication'),
        ),
        migrations.AlterField(
            model_name='aigeneration',
            name='model_used',
            field=models.CharField(default='gpt-4.1-nano', help_text='OpenAI model used', max_length=100),
        ),
        migrations.AlterField(
            model_name='aigeneration',
            name='output_text',
            field=models.TextField(help_text='AI-generated content'),
        ),
        migrations.AlterField(
            model_name='aigeneration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aigeneration',
            index=models.Index(fields=['user', '-created_at'], name='ai_services_user_id_16edf2_idx'),
        ),
        migrations.AddIndex(
            model_name='aigeneration',
            index=models.Index(fields=['application'], name='ai_services_applica_5cd984_idx'),
        ),
    ]
