# Generated by Django 6.0.1 on 2026-01-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_alter_aigeneration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneration',
            name='generation_type',
            field=models.CharField(choices=[('tailored_resume', 'Tailored Resume'), ('cover_letter', 'Cover Letter'), ('interview_prep', 'Interview Preparation'), ('skills_analysis', 'Skills Analysis')], max_length=20),
        ),
    ]
