# Generated by Django 6.0.1 on 2026-01-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_alter_aigeneration_generation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneration',
            name='generation_type',
            field=models.CharField(choices=[('tailored_resume', 'Tailored Resume'), ('cover_letter', 'Cover Letter'), ('interview_prep', 'Interview Preparation'), ('match_score', 'Match Score')], max_length=20),
        ),
    ]
